import type { BenchDb } from '../../src/bench-schema.js';
import { newId } from '../../src/ids.js';

/**
 * A small, hand-built world covering every visibility rule and its negation.
 *
 * Deliberately not generated by the bench loader: the loader draws at random,
 * and a test that asserts the tag seal needs a moderator who is *provably* not
 * in the tag, not one who happens not to be this run.
 */
export interface VisibilityFixture {
  orgId: string;
  otherOrgId: string;
  /** Author of every prayer below. */
  authorId: string;
  /** Plain member of the church, in the group, not in the tag. */
  groupMemberId: string;
  /** Plain member of the church, in the tag, not in the group. */
  tagMemberId: string;
  /** Plain member of the church, in neither the group nor the tag. */
  outsiderId: string;
  /** Church moderator, in neither the group nor the tag. */
  moderatorId: string;
  /** Church super_user, in neither the group nor the tag. */
  superUserId: string;
  /** Church moderator who IS also in the group. */
  moderatorInGroupId: string;
  /** Member of a different church entirely. */
  foreignerId: string;

  groupId: string;
  tagId: string;

  churchPostId: string;
  groupPostId: string;
  tagPostId: string;
  groupAndTagPostId: string;
  authorOnlyPostId: string;
}

export async function buildVisibilityFixture(
  db: BenchDb,
  slug: string,
): Promise<VisibilityFixture> {
  const orgId = newId();
  const otherOrgId = newId();
  await db
    .insertInto('orgs')
    .values([
      { id: orgId, slug, display_name: `Fixture (${slug})` },
      { id: otherOrgId, slug: `${slug}-other`, display_name: `Fixture other (${slug})` },
    ])
    .execute();

  const person = (
    label: string,
  ): { id: string; supabase_auth_id: string; email: string; display_name: string } => {
    const id = newId();
    return {
      id,
      supabase_auth_id: newId(),
      email: `${label}.${id}@fixture.invalid`,
      display_name: label,
    };
  };

  const author = person('author');
  const groupMember = person('group-member');
  const tagMember = person('tag-member');
  const outsider = person('outsider');
  const moderator = person('moderator');
  const superUser = person('super-user');
  const moderatorInGroup = person('moderator-in-group');
  const foreigner = person('foreigner');

  await db
    .insertInto('users')
    .values([
      author,
      groupMember,
      tagMember,
      outsider,
      moderator,
      superUser,
      moderatorInGroup,
      foreigner,
    ])
    .execute();

  await db
    .insertInto('user_orgs')
    .values([
      { user_id: author.id, org_id: orgId, role: 'member' },
      { user_id: groupMember.id, org_id: orgId, role: 'member' },
      { user_id: tagMember.id, org_id: orgId, role: 'member' },
      { user_id: outsider.id, org_id: orgId, role: 'member' },
      { user_id: moderator.id, org_id: orgId, role: 'moderator' },
      { user_id: superUser.id, org_id: orgId, role: 'super_user' },
      { user_id: moderatorInGroup.id, org_id: orgId, role: 'moderator' },
      { user_id: foreigner.id, org_id: otherOrgId, role: 'member' },
    ])
    .execute();

  const groupId = newId();
  await db
    .insertInto('groups')
    .values({ id: groupId, church_id: orgId, name: 'Fixture Group' })
    .execute();
  await db
    .insertInto('group_members')
    .values([
      { group_id: groupId, user_id: groupMember.id, role: 'member' },
      { group_id: groupId, user_id: moderatorInGroup.id, role: 'member' },
    ])
    .execute();

  // The author owns the tag but is NOT a member of it — mirrors the real shape
  // and makes the author clause load-bearing rather than decorative.
  const tagId = newId();
  await db
    .insertInto('tags')
    .values({ id: tagId, owner_id: author.id, church_id: orgId, name: 'fixture tag' })
    .execute();
  await db.insertInto('tag_members').values({ tag_id: tagId, user_id: tagMember.id }).execute();

  const deadline = new Date(Date.now() + 24 * 60 * 60 * 1000);
  const post = (
    label: string,
  ): {
    id: string;
    org_id: string;
    parent_id: null;
    author_id: string;
    body: string;
    status: 'published';
    edit_deadline: Date;
  } => ({
    id: newId(),
    org_id: orgId,
    parent_id: null,
    author_id: author.id,
    body: `fixture ${label}`,
    status: 'published',
    edit_deadline: deadline,
  });

  const churchPost = post('church');
  const groupPost = post('group');
  const tagPost = post('tag');
  const groupAndTagPost = post('group+tag');
  const authorOnlyPost = post('author-only');

  await db
    .insertInto('posts')
    .values([churchPost, groupPost, tagPost, groupAndTagPost, authorOnlyPost])
    .execute();

  await db
    .insertInto('post_audiences')
    .values([
      { post_id: churchPost.id, church_id: orgId, group_id: null, tag_id: null },
      { post_id: groupPost.id, church_id: null, group_id: groupId, tag_id: null },
      { post_id: tagPost.id, church_id: null, group_id: null, tag_id: tagId },
      { post_id: groupAndTagPost.id, church_id: null, group_id: groupId, tag_id: null },
      { post_id: groupAndTagPost.id, church_id: null, group_id: null, tag_id: tagId },
      // authorOnlyPost deliberately gets no audience rows.
    ])
    .execute();

  return {
    orgId,
    otherOrgId,
    authorId: author.id,
    groupMemberId: groupMember.id,
    tagMemberId: tagMember.id,
    outsiderId: outsider.id,
    moderatorId: moderator.id,
    superUserId: superUser.id,
    moderatorInGroupId: moderatorInGroup.id,
    foreignerId: foreigner.id,
    groupId,
    tagId,
    churchPostId: churchPost.id,
    groupPostId: groupPost.id,
    tagPostId: tagPost.id,
    groupAndTagPostId: groupAndTagPost.id,
    authorOnlyPostId: authorOnlyPost.id,
  };
}
